//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class atractivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public atractivo()
        {
            this.atractivo_has_criterios_evaluacion = new HashSet<atractivo_has_criterios_evaluacion>();
        }
    
        public int id_Atractivo { get; set; }
        public int id_Pueblo_magico { get; set; }
        public int id_Tipo_atractivo { get; set; }
        public double latitud { get; set; }
        public double longitud { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atractivo_has_criterios_evaluacion> atractivo_has_criterios_evaluacion { get; set; }
        public virtual pueblo_magico pueblo_magico { get; set; }
        public virtual tipo_atractivo tipo_atractivo { get; set; }
    }
}
