//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calificacion
    {
        public int id_Calificacion { get; set; }
        public int id_Atractivo { get; set; }
        public int id_Criterios_evaluacion { get; set; }
        public int id_Pueblo_magico { get; set; }
        public int id_Usuario { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public double calificacion1 { get; set; }
    
        public virtual atractivo_has_criterios_evaluacion atractivo_has_criterios_evaluacion { get; set; }
        public virtual historial_visitas historial_visitas { get; set; }
    }
}
